### ISSUE TITLE
Which Hardware Versions?

### ISSUE THREAD

**Issue by tcurdt** [scottalford75/Remora-NVEM#1]
Can you confirm which hardware versions should work?
I've seen the following boards around:

- NVEMV1.1
- NVEMV2.1

Would be great to have this added to the README.

**Comment by scottalford75** [comment]
There looks to be some differences in the versions of the board with the key difference being the Ethernet PHY chip used. V2 and V3 boards use an 8720A PHY chip where as the V1 boards look to use a DP83846.

Therefore the Remora-NVEM firmware should work on the V2 and V3 boards and not the V1 boards.

**Comment by tcurdt** [comment]
Would you accept a PR to add this to the README?
