### ISSUE TITLE
Building with PlatformIO

### ISSUE THREAD

**Issue by tcurdt** [scottalford75/Remora-NVEM#2]
Any chance of building the project with PIO?

I wanted to give it a try but  I am still a bit lost what needs to go into the firmware itself. These?

```
Core
Drivers/STM32F2xx_HAL_Driver
Drivers/CMSIS
LWIP/App
LWIP/Target
Middlewares/Third_Party/LwIP
```

**Comment by scottalford75** [comment]
I'm guessing it's possible but the only time I've used PlatformIO is with the Mbed framework. 

Maybe some hints here:

https://docs.platformio.org/en/stable/frameworks/stm32cube.html

The drivers and middleware maybe pulled in automatically?
